config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # configuracion de rutas 

  #  http://127.0.0.1:3000/static_pages/home
  #  http://127.0.0.1:3000/static_pages/help

  # primera pag que ve el usuario
  root "static_pages#home"

  # rutas relativas a root ... 
  get  "/help",    to: "static_pages#help"  # internamente va hacia http://127.0.0.1:3000/static_pages/help
  get  "/about",   to: "static_pages#about" # pero en el navegador basta con llamar http://127.0.0.1:3000/help
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "users#new"

  # rutas asociadas al loggin ... 
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  # entidades de la bd 
  resources :users

  # controlador de reactivaciones, solo permite la accion :edit
  resources :account_activations, only: [:edit]

  # help_path
  # about_path
  # contact_path
  # Define your 
  # application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "application#hello"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <%# config routest, ver: routes.rb %>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%# partial 1. %>
    <%= render 'layouts/shim'  %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
       <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      
      <ul id="navbar-menu"
          class="nav navbar-nav navbar-right collapse navbar-collapse">

        <%# config routest, ver: routes.rb %>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" id="account" class="dropdown-toggle">
              Account <b class="caret"></b>
            </a>

            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete } %>
              </li>
            </ul>

          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <%= render 'layouts/head' %>
  <body>

    <%# partials: bloque de codigo html llamado como una funcion  %>
    <%# partial 2. %>
    <%= render 'layouts/header' %>

    <%# libreria js %>
    <%= javascript_importmap_tags %>
    <div class="container">
     <%# asociado con el flash declarado en users_controller.rb ... create  %>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%# contenido de las views %>
      <%= yield %>  
      <%# partial 3. %>
      <%= render 'layouts/footer' %>

      <%# solo se mostrara en ambiente de desarrollo %>
      <%# <%= @user.name%> %>
      <%# <%= Time.now%> %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>